---
title: "Experimental Psycholinguistics"
output: html_document

---
<link rel="stylesheet" type="text/css" href="styles/main.css">
<link rel="stylesheet" type="text/css" href="styles/textfolding.css">


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Welcome to the course!

<button type="button" class="collapsible">
Week 36: Introduction
</button>
<div class="content">

##### Tuesday Lecture:

- Introduction to the course
- Introduction to a cognitive construct: working memory

##### Thursday Lab:

- Participate in-class online memory-span experiment
- Discuss infrastructure involved in an online experiment

##### Homework:

- Read chapters from <a href="https://learnstatswithjasp.com" target="_blank"> Navarro, Foxcroft & Faulkenberry (2019) </a>
	- Chapter 1
	- Chapter 2
- Read chapters from Hinklelman & Kempthorne (2008)
	- Chapter 1 (Ok to skim some)
	- Chapter 2 (Ok to skim some, especially the math. I have highlighted key points)
	- Chapter 2 section 2.7 (Essential reading!)
- Read Gluck et al Chapter 9 (9.1 required, rest optional)
- Install software  
		- <a href="https://osdoc.cogsci.nl/3.3/download/" target="_blank"> OpenSesame </a>  
		- <a href="https://jasp-stats.org/download/" target="_blank"> JASP </a>  
- Watch and do the <a href="https://osdoc.cogsci.nl/3.3/tutorials/beginner/" target="_blank"> OpenSesame beginner tutorial </a>
</div>
<p></p><p></p>


[//]: # (*******************************************************************************************************************)

<button type="button" class="collapsible">
Week 37: Experimental Design 1 
</button>
<div class="content">

##### Tuesday Lecture:
- Discuss experimental design at the conceptual level (chapters from Hinklelman & Kempthorne, 2008; Navarro & Foxcroft, 2018)
- Discussion on operationalization
  - Predictor and Outcome variables (IV's and DV's)
	- Scales of measurement (Nominal, Ordinal, Interval, Ratio)
	- Randomization
	- Controls
	- Samples and populations
- Discuss operationalization of working memory in the memory span task

##### Thursday Lab:
- Anatomy of an OpenSesame experiment
  - Discuss tutorial: questions and answers
  - Dissect structure of the Memory Span experiment
		
##### Homework:
- Read Sternberg (1966)
- Identify the sentences in which Sternberg justifies and operationalizes his experiment


</div>
<p></p><p></p>


[//]: # (*******************************************************************************************************************)


<button type="button" class="collapsible">
Week 38: Experimental Design 2
</button>
<div class="content">

##### Tuesday Lecture:
- Recap operationalization from last week
- Discuss how Sternberg justifies and operationalizes his experiment
	
##### Thursday Lab:
- Brainstorm how to construct a task that would measure whether we access working memory in serial or parallel
- Discuss how this could be implemented in OpenSesame

		
##### Homework:
- **Porfolio Assignment 1** (due next week):
		- Summarize a published experiment (Loosli et al (2012):    
			- Justification  
			- Operationalization  
				- Participants (demographic data)  
				- DV’s  
				- IV’s  
			- Data type (Continous, Interval, etc.)  
			- Experimental design  
			- Analysis methods  
			- Conclusions  
			- Possible confounds  
- Read:
	- (Optional: Navarro et al (2019) chapter 6)
	- (Optional: Navarro et al (2019) chapter 7)
	- Required: Navarro et al (2019) chapter 8

</div>
<p></p><p></p>

[//]: # (*******************************************************************************************************************)


<button type="button" class="collapsible">
Week 39 Analysis 1: Significance testing  
PA 1 due
</button>
<div class="content">

##### Tuesday Lecture:
- lecture on: 
	- statistical models (modelling relationships)
	- variation
	- distributions
	- test statistics
	- prediction
	- null and alternative hypotheses
	- p-values
	- means
	- standard deviations
	- degrees of freedom
	- logic of NHST

##### Thursday Lab:
- Build a Sternberg experiment in OpenSesame together
- Everyone runs their Sternberg experiment locally on their computer and uploads their data

##### Homework:
- Read Navarro et al (2019) chapter 10
	- bare minimum: read the summary (10.10)
	- a bit more: read 10.3 and 10.5
	- optional: all of chapter 10



</div>
<p></p><p></p>

[//]: # (*******************************************************************************************************************)


<button type="button" class="collapsible">
Week 40: Models of Working Memory
</button>
<div class="content">

##### Tuesday Lecture:
- Discuss PA1
- Review logic of NHST



##### Thursday Lab:
- t-tests
- We do t-tests together in JASP
- We do t-tests on our Sternberg data


##### Homework:
- Analyze a provided dataset (t-test)
  - Do analysis in JASP
  - Produce an appropriate figure
  - Report the results in APA style
- Read Navarro et al (2019) chapter 12 (Sections 12.1 - 12.5)
- **Porfolio Assignment 2** (due next week):
  - Find a working memory or attention experiment (or portion of an experiment) that you will replicate using OpenSesame
      - Identify IV's and Dv's
      - What are the stimuli?
      - What is the response?
      - How will your version differ from the original?
      - Other important details?

</div>
<p></p><p></p>


[//]: # (*******************************************************************************************************************)

<button type="button" class="collapsible">
Week 41: Analysis 2: Cumulative Science  
PA 2 due
</button>
<div class="content">

##### Tuesday Lecture:
- Review t-tests
- Cumulative Science: meta-analysis

##### Thursday Lab:
- ANOVAs
- We do ANOVAs together in JASP

##### Homework:
- Analyze a provided dataset (ANOVA)
  - Do analysis in JASP
  - Produce an appropriate figure
  - Report the results in APA style
- Read Navarro et al (2019) chapter 11 (sections 11.1 - 11.3)

</div>
<p></p><p></p>


[//]: # (*******************************************************************************************************************)

<button type="button" class="collapsible" style="background-color: #feb24c">
Week 42: Autumn Break <span style="font-size:32px">&#127810;</span>
</button>
<div class="content">


##### Homework:

- Relax


</div>
<p></p><p></p>


[//]: # (*******************************************************************************************************************)


<button type="button" class="collapsible">
Week 43: Analysis 3: Refining a research question
</button>
<div class="content">


##### Tuesday Lecture:
- review ANOVAs
- Refining research questions



##### Thursday Lab:
- Correlations
- We do correlations together in JASP

##### Homework:
- **Porfolio Assignment 3** (due next week):
  - Analyze three provided data sets in JASP:
    - t-test
    - ANOVA
    - corrrelation

</div>
<p></p><p></p>

[//]: # (*******************************************************************************************************************)


<button type="button" class="collapsible">
Week 44: Build and pilot an experiment 1  
PA 3 due
</button>
<div class="content">

##### Tuesday Lecture:
- review correlations

##### Thursday Lab:
- we help each other build and pilot our experiments

##### Homework:
- build and pilot our experiments


</div>
<p></p><p></p>

[//]: # (*******************************************************************************************************************)


<button type="button" class="collapsible">
Week 45: Build and pilot an experiment 2
</button>
<div class="content">

##### Tuesday Lecture:
- Discuss PA3


##### Thursday Lab:
- we help each other build and pilot our experiments

##### Homework:
- build and pilot our experiments


</div>
<p></p><p></p>


[//]: # (*******************************************************************************************************************)


<button type="button" class="collapsible">
Week 46: Run your experiment  
</button>
<div class="content">

##### Tuesday Lecture:
- Reading and Working Memory

##### Thursday Lab:


##### Homework:



</div>
<p></p><p></p>


[//]: # (*******************************************************************************************************************)


<button type="button" class="collapsible">
Week 47: Analyze your data 
</button>
<div class="content">

##### Tuesday Lecture:
- Research ethics

##### Thursday Lab:


##### Homework:
- **Porfolio Assignment 4** (due next week):
  - Analyze your own data
    - appropriate figures
    - appropriate statistics
    - report results in APA style


</div>
<p></p><p></p>


[//]: # (*******************************************************************************************************************)


<button type="button" class="collapsible">
Week 48: Interpret your data 1  
PA 4 due
</button>
<div class="content">

##### Tuesday Lecture:


##### Thursday Lab:


##### Homework:
- Read Wetzels et al (2011)


</div>
<p></p><p></p>


[//]: # (*******************************************************************************************************************)


<button type="button" class="collapsible">
Week 49: Interpret your data 2
</button>
<div class="content">

##### Tuesday Lecture:
- discuss PA 4
- interpretation of results

##### Thursday Lab:


##### Homework:
- **Porfolio Assignment 5** (due next week):
  - Report your results in a brief scientific paper
    - Abstract
    - Introduction
    - Results
    - Discussion
    - References (APA style)


</div>
<p></p><p></p>


[//]: # (*******************************************************************************************************************)


<button type="button" class="collapsible">
Week 50: Report your experiment  
PA 5
</button>
<div class="content">

##### Tuesday Lecture:


##### Thursday Lab:


##### Homework:



</div>
<p></p><p></p>

<a href="https://drive.google.com/drive/folders/1M2FJjgKZ46uZPs0SJlCv_Icjqs7zSf_d?usp=sharing" target="_blank"> Slides </a>

<a href="https://ethanweed.github.io/teaching/Recommendations.html" target="_blank">Recommended Textbooks and Software</a>





<script src="styles/textfolding.js"></script>

